name: integration-tests

# on: pull_request
on:
  push:
    branches:
      - "feature/integration-tests"

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - 
        uses: actions/checkout@v2
      - 
        name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0
        with:
          config: ./integration-tests/kind-config.yaml
      -
        name: Setup Registry
        run: ./integration-tests/setup-registry.sh
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      -
        uses: azure/setup-kubectl@v2.0
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build Image Name
        run: | 
          GIT_SHA=$(git rev-parse --short HEAD)
          echo "IMAGE_NAME=localhost/ado-agent-orchestrator:${GIT_SHA}" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}
      -
        name: Run Integration Test
        env:
          # In the future, investigate a better place to set this
          ADO_PROJECT: hol
          PIPELINE_NAME: pipeline-test
        run: |
          ./integration-tests/test-deployment.sh ${{ env.IMAGE_NAME }} \
            ${{ secrets.ORG_URL }} \
            ${{ secrets.ORG_PAT }} \
            ${{ env.ADO_PROJECT }} \
            ${{ env.PIPELINE_NAME }}